apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-deployment
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image:  poojithachiruve/hello-world-jvm
        ports:
        - containerPort: 8000
       
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
  labels:
    app: hello-world
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    nodePort: 32121
  selector:
    app: hello-world
